default:
  image: alpine:latest
before_script:
  - apk --update add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
stages:
- deploy-stage
- deploy-prod
- lhci
- test
cache:
  paths:
  - node_modules/
deploy-stage:
  stage: deploy-stage
  only:
  - develop
  script:
  - echo "Deploying to Stage"
  - ssh $SSH_USER@$SSH_SERVER "cd /srv/stage.0to100.ink/ && git pull && npm i && npm run build"
deploy-prod:
  stage: deploy-prod
  only:
  - master
  script:
  - echo "Deploying to Prod"
  - ssh $SSH_USER@$SSH_SERVER "cd /srv/0to100.ink/ && git pull && npm i && npm run build"
lhci:
  stage: lhci
  image: cypress/browsers:node12.6.0-chrome77
  only:
  - master
  script:
  - npm install -g @lhci/cli@0.3.x
  - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox"
    --collect.url=https://0to100.ink || echo "LHCI failed!"
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
